language: java
os: linux
jdk:
  - openjdk11

sudo: false
before_install:
  - chmod +x mvnw
  - mvn clean
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P dev
script:
  - mvn clean test jacoco:report coveralls:report -P dev
  - mvn compile jib:build -P dev
env:
  global:
    - secure: nxoa/NFa0kfZiHS3NZ5NyZGh21RLabNZVdDEBu7Xnpc33Cyb5858OePLxtndDg/AHeOjNH8DJ3NWLEuRkX/WNOkgOhgeldyIAqrqS+33jSneAzY98J6Ab5rvCyJq9Jf6IwtIMmGTn5yqG6myHpC3eJz+iPzfrXw7/e5uIdJ0AaRXL50gsFadHlPwsZ5eXgFAfCbivf3HcE6PTp8me3NkavoFQnsCkWMbJ08TYeewo8uDtZ/cmFmQTSrA0dCdXVOmiydISeFcW17SzV6sqtN6VCLrr6BQR9Qded1NpOCAPZUJjoPKXeJFAk8FvdXcmzBNKZLkMKpMR5CeM8/17DjW43thFjj7AP41BCzy0z9b/WEZUdLrT/y3RaDssKBxKXkrl81kjxYyQQmk1xU13MMBCG9GiTefmtqSzPQt9ovAnFcnr1HTTULUXQtJKzqCQswAf3LaxjH7LUBMf2foi936wVZXCbuB3Z+ZHINTvAcQC5j1M+KL73uJwM+ad+IQbg74URRcwFE0yU3tY4qgMvSqIZrxN3IG0Ubm66PfJ4OsyyYNQV5TotkTqMz0T/RJS5RtcWpc74NpO8bdzaNYcZmG7tKKv6levyqlNngFMq3qMjdH0m8jIr+YdRM7r1UUMbVbnluZcXC/AQ6klcGrvjXEFOeqBmvnvbpi1/Wkpp3xrEU=
    - secure: F7o01M1lxpov8Q1RFwXfCMhjoHssClV0kkCdJ3u5/uDL2uiZcPS2FgNEGj5l8kvjNJGWijxt3vZoFSqwVsKHWCgLybc0yD6iVBduW361WmSYBSFQmSXOoWMEs5xARsAso+jymLBdsr0fzzCS6OqdS8e5xiqfm/+s/YDyzD8i0Rc6skTQgYU4oj/hm59CcDrqBd3Z7k7F68shhphqnRF8cGhLjFMm8eXEu2pBqlocqnVdElKMBXSQdBr7dPRc/recs8g9QBolJJqpvNqT4I6WpNxvrQ0LX/W/GBVM2cAhpOa6Ft8JIvnUkdYjQAE5M4bEpuZnYJBhfOIvABK6wsivgBc4Jd0hXFHjdXlFAkwgZT/YisOe4krbA2+cy1co5P06aXcIB4T4aw43J02A65uzNhocP+AjFGS5jXmKK/G2SW14qp5xNibxcsmoA/P6Z1W8JLTNlLdBViktA0nhu315KgD05dwEsNdt7lbp3m9XuT82nlifZWcdU6bjDRfSMbLZJ1+1CIxsGxwdaQFPSazBIbTqwUKwTqFJ2L/ENzYu0YVwXM+/5D7zFwwFZkGSn7v7MxQGZnxnUgdZUfvBe2iQ/waz7EGvlaNUNJxwMRwF5ava6qyf4rweXCznrCPeMp+2DTi9XshsN/P5ZOn7/mkX6gWHI0oj0b1fhgU8mx49k3c=
