spring:
    datasource:
        url: ${POSTGRES_URL}
        driverClassName: org.postgresql.Driver
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        hibernate:
            ddl-auto: create

management:
    server:
        port: 8081
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: "*"
    endpoint:
        metrics:
            enabled: true
      
     