INSERT INTO CUSTOMER (ID, CUSTOMER_ID, DATE_OF_BIRTH, AGE, FIRST_NAME, LAST_NAME) VALUES ('1001', 1001, PARSEDATETIME('2000-01-20', 'yyyy-MM-dd'), 20, 'John', 'Doe');

INSERT INTO ADDRESS (CUSTOMER_ID, STREET, HOUSE_NUMBER, CITY, ZIP_CODE) VALUES ('1001', 'SOMESTREET', '200', 'Amsterdam', '1928ZP');

INSERT INTO CUSTOMER (ID, CUSTOMER_ID, DATE_OF_BIRTH, AGE, FIRST_NAME, LAST_NAME) VALUES ('1002', 1002, PARSEDATETIME('1991-12-01', 'yyyy-MM-dd'), 28, 'Charles', 'Bailey');

INSERT INTO ADDRESS (CUSTOMER_ID, STREET, HOUSE_NUMBER, CITY, ZIP_CODE) VALUES ('1002', 'SOMESTREET', '420', 'Utrecht', '2928ZP');

INSERT INTO CUSTOMER (ID, CUSTOMER_ID, DATE_OF_BIRTH, AGE, FIRST_NAME, LAST_NAME) VALUES ('1003', 1003, PARSEDATETIME('1995-01-11', 'yyyy-MM-dd'), 25, 'Chloe', 'Forsyth');

INSERT INTO ADDRESS (CUSTOMER_ID, STREET, HOUSE_NUMBER, CITY, ZIP_CODE) VALUES ('1003', 'SOMESTREET', '103a', 'De Hauge', '3928ZP');

INSERT INTO CUSTOMER (ID, CUSTOMER_ID, DATE_OF_BIRTH, AGE, FIRST_NAME, LAST_NAME) VALUES ('1004', 1004, PARSEDATETIME('1957-11-23', 'yyyy-MM-dd'), 62, 'Selman', 'Schriemer');

INSERT INTO ADDRESS (CUSTOMER_ID, STREET, HOUSE_NUMBER, CITY, ZIP_CODE) VALUES ('1004', 'Kastanjestraat', '137', 'Schagen', '1741WK');

INSERT INTO CUSTOMER (ID, CUSTOMER_ID, DATE_OF_BIRTH, AGE, FIRST_NAME, LAST_NAME) VALUES ('1005', 1005, PARSEDATETIME('1987-03-14', 'yyyy-MM-dd'), 32, 'Rik', 'Rik');

INSERT INTO ADDRESS (CUSTOMER_ID, STREET, HOUSE_NUMBER, CITY, ZIP_CODE) VALUES ('1005', 'Postweg', '81', 'Buren', '9164LS');
