INSERT INTO CUSTOMER (ID,AGE,CURRENT_ADDRESS,FIRST_NAME,LAST_NAME) VALUES ('1001',20,'Amsterdam','John','Doe');
INSERT INTO CUSTOMER (ID,AGE,CURRENT_ADDRESS,FIRST_NAME,LAST_NAME) VALUES ('1002',28,'Utrecht','Charles','Bailey');
INSERT INTO CUSTOMER (ID,AGE,CURRENT_ADDRESS,FIRST_NAME,LAST_NAME) VALUES ('1003',25,'De Hauge','Chloe','Forsyth');
INSERT INTO CUSTOMER (ID,AGE,CURRENT_ADDRESS,FIRST_NAME,LAST_NAME) VALUES ('1004',62,'Kastanjestraat 137, 1741 WK  Schagen','Selman','Schriemer');
INSERT INTO CUSTOMER (ID,AGE,CURRENT_ADDRESS,FIRST_NAME,LAST_NAME) VALUES ('1005',32,'Postweg 81 9164 LS  Buren','Rik','Rik');